#!/bin/bash
# Script generated by LSD
echo "Processing 3 configuration files in up to 3 parallel processes..."
if [ "$1" = "" ]; then LSD_EXEC="/Users/emmanueltsallis/Documents/GitHub/Lsd/Work/jeec_lsd8/lsdNW"; else LSD_EXEC="$1"; fi
if [ "$2" = "" ]; then LSD_CONFIG_PATH="/Users/emmanueltsallis/Documents/GitHub/Lsd/Work/jeec_lsd8/Data_analysis/Base_scen"; else LSD_CONFIG_PATH="$2"; fi
echo "LSD executable: $LSD_EXEC"
echo "Configuration path: $LSD_CONFIG_PATH"
echo "Use Sim.sh LSD_EXEC CONFIG_PATH to change default paths"
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sim_1.lsd -p -l "$LSD_CONFIG_PATH"/Sim_1.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sim_2.lsd -p -l "$LSD_CONFIG_PATH"/Sim_2.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sim_3.lsd -p -l "$LSD_CONFIG_PATH"/Sim_3.log &
echo "3 log files being generated: Sim_1.log to Sim_3.log ."
